
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: ghcr.io/kubesphere-sigs/ks-releaser
  newName: ghcr.io/kubesphere-sigs/ks-releaser
  newTag: v0.0.15

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
